### ISSUE TITLE
Add an English WOTD

### ISSUE THREAD

**Issue by Squybee** [andrei1489/word-of-the-day#1]
It would be nice if an English WOTD was added.
Here is a RSS feed: https://www.merriam-webster.com/wotd/feed/rss2

**Comment by andrei1489** [comment]
Unfortunately, not all rss feeds are created equal. Will see what I can do.

**Comment by andrei1489** [comment]
Also, the system is built around having a foreign word, a translation, an example sentence and a translated example sentence, so I do not really see a way to implement english wotd at the moment.

**Comment by andrei1489** [comment]
Resolved by 42374d5 and ed9f0d8. Added english language from merriam-webster, but unfortunately there is no way to parse the data for example sentences in a reliable way.
